// Returns the WebP variant URL for a product image hosted on piszemy.com.pl S3.
// Variants generated by piszemy-image-optimizer Lambda:
//   foo.JPG  → foo.webp (full transcode), foo-600w.webp, foo-1200w.webp
//   foo.webp → foo-600w.webp, foo-1200w.webp (source kept as the full-size webp)
// Non-product URLs and unrecognized formats are returned unchanged.
export function webpUrl(url: string | undefined | null, variant: '' | '-600w' | '-1200w' = ''): string {
  if (!url) return '';
  const m = url.match(/^(.+\/products\/[^?#]+?)(\.(?:jpe?g|png|webp))(\?.*)?$/i);
  if (!m) return url;
  if (variant === '') {
    // Full-size: webp source IS the full-size; non-webp source has a foo.webp transcode.
    return /\.webp$/i.test(m[2]) ? url : `${m[1]}.webp${m[3] || ''}`;
  }
  return `${m[1]}${variant}.webp${m[3] || ''}`;
}

// Whether the given URL is a product image with responsive WebP variants.
export function hasWebpVariants(url: string | undefined | null): boolean {
  if (!url) return false;
  return /\/products\/[^?#]+\.(jpe?g|png|webp)(\?|$)/i.test(url);
}
